baseurl = "https://chriskirkland.github.io/chriskirkland.us/"
languageCode = "en-us"
title = "Chris Kirkland"
theme = "blackburn"
author = "Chris Kirkland"
copyright = "&copy; 2016. All rights reserved"
canonifyurls = true
paginate = 5

[params]
  # Shown in the home page
  subtitle = "Software Engineer / Math Nerd / Barbershop Enthusiast"
  dateFormat = "02 Jan 2006"
  googleAnalytics = "UA-123-45"
  highlightjs = "hybrid"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    identifier = "home"
    weight = 0
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    identifier = "post"
    weight = 1
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    identifier = "about"
    weight = 2
    url = "/about/"
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-paperclip fa-fw'></i>"
    identifier = "resume"
    weight = 3
    url = "resume.pdf"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    identifier = "contact"
    weight = 4
    url = "/contact/"

[social]
  linkedin = "chris-kirkland-44144621"
  github = "chriskirkland"
