apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-hugo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: website-hugo
    spec:
      containers:
      - name: nginx
        image: chriskirkland/website-hugo:latest
        ports:
        - containerPort: 80
        command: ["nginx", "-g", "daemon off;"]
